In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
from IPython.display import set_matplotlib_formats
import matplotlib.ticker
 
set_matplotlib_formats ('png')

def funcForFormatter (x, pos):
    if round(x) == x:
        return f"{round(x)}"
    
    return ""

def my_plot (x, y, xerr = 0, yerr = 0, title="", xlabel="", ylabel="", number=1, x_isint=False):
    
    x = np.array (x)
    y = np.array (y)

    k, s = np.polyfit (x, y, deg=1, cov=True)

    plt.figure()

    fig, ax1 = plt.subplots(figsize=(16, 16), dpi=100)

    ax1.set_title (title)

    ax1.set_ylabel (ylabel) 
    ax1.set_xlabel (xlabel)

    # ax1.scatter (x1, y1, marker=".", s = 100)

    if x_isint:
        formatter = matplotlib.ticker.FuncFormatter(funcForFormatter)

        ax1.xaxis.set_major_formatter (formatter)

    plt.errorbar (x, y, yerr=yerr, xerr=xerr, fmt='o-', ecolor='red', ls='none')

    ax1.plot (x, np.poly1d (k)(x))

    plt.savefig(f"./picturies/graph{number}.png", dpi=100)
    plt.grid()
    plt.show()

    return k, s

/tmp/ipykernel_55118/3925916254.py:8: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats ('png')


In [2]:
f = 30 #см

In [4]:
nu1 = 1 #MГц
nu2 = 2
nu3 = 3
nu4 = 3.5

Xm - в делениях

In [5]:
x1 = list (map (int, input().split()))
x1

[8, 77, 48]

In [6]:
x2 = list (map (int, input().split()))
x2

[44, 83, 4]

In [7]:
x3 = list (map (int, input().split()))
x3

[72, 80, 79]

In [8]:
x4 = list (map (int, input().split()))
x4

[84, 74, 63]

Подгон, т.к. есть переход через 0

In [9]:
x1[0] += 100
x2[0] += 100
x3[0] += 200
x3[1] += 100
x4[0] += 200
x4[1] += 100

In [10]:
x1 = np.array (x1)
x2 = np.array (x2)
x3 = np.array (x3)
x4 = np.array (x4)

In [11]:
print (x1, x2, x3, x4)

[108  77  48] [144  83   4] [272 180  79] [284 174  63]


Конец подгона

In [12]:
lm = 640
d_lm = 20 # в нм

In [ ]:
k1, s1 = my_plot (x=[-1, 0, 1], y=x1 * 4, yerr=4, number=1, title="Зависимость x_m от m при частоте 1Мгц", xlabel="m", ylabel="x_m, мкм", x_isint=True)
k2, s2 = my_plot (x=[-1, 0, 1], y=x2 * 4, yerr=4, number=2, title="Зависимость x_m от m при частоте 2Мгц", xlabel="m", ylabel="x_m, мкм", x_isint=True)
k3, s3 = my_plot (x=[-1, 0, 1], y=x3 * 4, yerr=4, number=3, title="Зависимость x_m от m при частоте 3Мгц", xlabel="m", ylabel="x_m, мкм", x_isint=True)
k4, s4 = my_plot (x=[-1, 0, 1], y=x4 * 4, yerr=4, number=4, title="Зависимость x_m от m при частоте 3.5Мгц", xlabel="m", ylabel="x_m, мкм", x_isint=True)

In [14]:
print (k1, k2, k3, k4)

[-120.          310.66666667] [-280.  308.] [-386.  708.] [-442.          694.66666667]


In [17]:
d_k1 = s1[0][0] * 10
d_k2 = s2[0][0] / 10
d_k3 = s3[0][0] / 5
d_k4 = s4[0][0] * 20

print (d_k1, d_k2, d_k3, d_k4)

53.33333333333058 43.20000000000027 21.60000000000064 26.666666666673642


In [24]:
lm_m = [0, 0, 0, 0]

lm_m[0] = abs(k1[0])
lm_m[1] = abs(k2[0])
lm_m[2] = abs(k3[0])
lm_m[3] = abs(k4[0])

lm_m = np.array (lm_m)

for i in lm_m:
    print (i)
 # в мкм

120.0
280.0
386.00000000000006
442.0


In [30]:
L = f * lm / (lm_m / 10 ** 4) / 10 ** 3
d_L = np.array ([d_k1, d_k2, d_k3, d_k4])
print (L, d_L) #мкм

[1600.          685.71428571  497.40932642  434.38914027] [53.33333333 43.2        21.6        26.66666667]


In [31]:
v = L * [1, 2, 3, 3.5]
d_v = d_L * [1, 2, 3, 3.5]
print (v, d_v) # в м/с

[1600.         1371.42857143 1492.22797927 1520.36199095] [53.33333333 86.4        64.8        93.33333333]


In [32]:
T = np.array([6, 7.2]) #10 дел - 1 мм
f = np.array([1.2, 1.07]) #МГц

In [37]:
L1 = 2 * T / 10 * 10 ** 3
d_L1 = 2 * np.array ([0.1, 0.1]) / 10 * 10 ** 3
print (L1, d_L1) #в мкм

[1200. 1440.] [20. 20.]


In [38]:
v1 = L1 * f
d_v1 = d_L1 * f
print (v1, d_v1)

[1440.  1540.8] [24.  21.4]
